### ISSUE TITLE
Develop better ACCs

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-vis/kagra-vis#11]
From #8

**Comment by MiyoKouseki** [comment]
takahashi-san did.
https://gwdoc.icrr.u-tokyo.ac.jp/cgi-bin/private/DocDB/ShowDocument?docid=11774

**Comment by MiyoKouseki** [comment]
@Ryutaro-T -san, Is this truly finished?

I think you and sato-san are making new LVDT coil adapter for new accelerometers.
Could you make new issues for it?

**Comment by Ryutaro-T** [comment]
This task includes following items;

- [x] Research of the position sensors. (Takahashi)
- [x] Preparation of the LVDT prototype. (Sato)
- [x] Test f the ACC prototype with LVDT. (Takahashi)
- [x] Evaluation of the ACC prototype at the KAGRA site. (Miyo, Takahashi)

**Comment by Ryutaro-T** [comment]
"Replacement of ACCs" should be made as new issue. Preparation of the LVDT coils is included in the issue.

**Comment by MiyoKouseki** [comment]
Thank you

**Comment by Ryutaro-T** [comment]
We have already #50.

**Comment by MiyoKouseki** [comment]
This issue was done.
https://gwdoc.icrr.u-tokyo.ac.jp/cgi-bin/private/DocDB/ShowDocument?docid=11774
