### ISSUE TITLE
Additional filters for the LVDT combiner.

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-vis/kagra-vis#39]
[From here](https://paper.dropbox.com/doc/Plan-for-the-long-brake-towards-O3c--A6BHN4gn~Ey5XkTLymY8BCZaAg-KqexeqMaCA7DITFGxA5ih)

What is this?

**Comment by Ryutaro-T** [comment]
Go to #74. This issue should be deleted.

**Comment by MiyoKouseki** [comment]
Close it because it is duplicating to #74.
