### ISSUE TITLE
Install new beams in the BS chamber

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-vis/kagra-vis#42]
[From here](https://paper.dropbox.com/doc/Plan-for-the-long-brake-towards-O3c--A6BHN4gn~Ey5XkTLymY8BCZaAg-KqexeqMaCA7DITFGxA5ih)

## To Do 
List up the To Do.

**Comment by Ryutaro-T** [comment]
This issue is the same as #73, and should be deleted.

**Comment by MiyoKouseki** [comment]
OK I close.
