### ISSUE TITLE
Installation of the new electronics (SG card, LVDT combiner, RS monitor)

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-vis/kagra-vis#65]
[from here](https://www.dropbox.com/s/60oygtwmckmdyj6/Towards%20O4%20on%20VIS%20.xlsx?dl=0)

Would you describe more detail?

Related Issues
#75

**Comment by Ryutaro-T** [comment]
This task should be broken to each task (SG cards,LVDT combiner, RS monitor).
This should be deleted.

**Comment by MiyoKouseki** [comment]
OK I close
