### ISSUE TITLE
Disassembling procedure of ETMY

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-vis/kagra-vis#67]
[from here](https://www.dropbox.com/s/60oygtwmckmdyj6/Towards%20O4%20on%20VIS%20.xlsx?dl=0)

**Comment by MiyoKouseki** [comment]
@NaohisaSato @Ryutaro-T 解体の手順書のリンクをここに貼ってもらえますか？

**Comment by NaohisaSato** [comment]
https://www.dropbox.com/scl/fi/1o44wd1hs3f5loi9coxmw/EY-Type-A-_rev2.xlsx?dl=0&rlkey=kkg5qn9f8mnhgc9swenx55wpl

**Comment by NaohisaSato** [comment]
@MiyoKouseki @Ryutaro-T  貼りました

**Comment by NaohisaSato** [comment]
@Ryutaro-T @MiyoKouseki  解体の手順書に、 Y-endに搬入する工具、物品のリストを加えました。（タブ「分解の為の物品移動」、あくまでも解体に必要な分です）

**Comment by NaohisaSato** [comment]
枕木やパレットはInventory Listにないので不明ですが、不足なら他所からEYVへ移動が必要
