### ISSUE TITLE
Test of modified ACC at the site

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-vis/kagra-vis#72]
[from here](https://www.dropbox.com/s/hoadb73fdyah02c/Post-O3%20task.xlsx?dl=0)

## Please describe divide your ticket into small tasks.
- [ ] aaa
- [ ] bbb
- [ ] ccc
- [ ] **Review**
- [ ] **Close**

**Comment by Ryutaro-T** [comment]
This task is included in another issue. This should be deleted.

**Comment by MiyoKouseki** [comment]
OK. I close it
