### ISSUE TITLE
Test of additional filters for the LVDT combiner

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-vis/kagra-vis#76]
[from here](https://www.dropbox.com/s/hoadb73fdyah02c/Post-O3%20task.xlsx?dl=0)

## Please describe divide your ticket into small tasks.
- [ ] aaa
- [ ] bbb
- [ ] ccc
- [ ] **Review**
- [ ] **Close**

**Comment by Ryutaro-T** [comment]
Go to #74. This issue should be deleted.

**Comment by MiyoKouseki** [comment]
Thank you. OK I close.
