### ISSUE TITLE
Change the way to bind cables between the payload and BF

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-vis/kagra-vis#86]
EYだけケーブルタイを替える。[資料](http://gwwiki.icrr.u-tokyo.ac.jp/JGWwiki/KAGRA/Subgroups/VIS/VISMinutes20201002?action=AttachFile&do=view&target=Cable+bandling+BF-CRYO.pdf)

ETMYは全部引き出すので、ついでにPayloadからのケーブルをVISで使っている固定方式に替える。か？

**Comment by MiyoKouseki** [comment]
[インターフェイスミーティング](http://gwwiki.icrr.u-tokyo.ac.jp/JGWwiki/KAGRA/Subgroups/VIS/VISMinutes20201002)

参加者：佐藤、高橋、牛場、阿久津、麻生、正田、木村、平田、三代

新方式にしたときのメリット・デメリット
 - Yaw方向のばね定数変わりそう。（どれぐらいゆったりできるか。）
 - インストールの効率があがる。

ケーブルのゆったり具合は改善する？
 - ロッドの中心ではなく外側で止めるのでその分余裕がある。

もし昔の固定方法に戻す場合、どれぐらい日数がかかるか？
 - 1週間かかる（ロッドから抜かないといけないので）

分割型にするほうがいいのでは？
 - これは時間がかかる

結論
 - 分割式にできるか考えるということに。

**Comment by MiyoKouseki** [comment]
@NaohisaSato @Ryutaro-T これっていつまでに分割式にできそうか判断をするんでしたっけ？

**Comment by MiyoKouseki** [comment]
[ミーティング](http://gwwiki.icrr.u-tokyo.ac.jp/JGWwiki/KAGRA/Subgroups/VIS/VISMinutes20201016)

YAW 方向の固定をすれば、OKということになった。

**Comment by MiyoKouseki** [comment]
@NaohisaSato @Ryutaro-T 新しいケーブルクランプはいつまでに作って、いつまでにインストールする予定ですか？

**Comment by NaohisaSato** [comment]
@MiyoKouseki @Ryutaro-T インストールはクライオパートがBFに接続される頃です（4月中旬）
下記スケジュールの＃88 Cabling がそれにあたると思います。
https://gwdoc.icrr.u-tokyo.ac.jp/DocDB/0114/L2011475/017/Schedule%20ETMY%20200807.pdf

**Comment by NaohisaSato** [comment]
10月16日ミーティングの指摘（ケーブルクランプが回転しないようにしっかり固定する）を反映し、DRAFT図面をアップロード。
https://gwdoc.icrr.u-tokyo.ac.jp/cgi-bin/private/DocDB/ShowDocument?docid=12141

**Comment by MiyoKouseki** [comment]
とりあえず、加工の発注が終わればこのTicketをCloseしたいと思います。
インストール時のTicketはまた近くなったら作ります。

**Comment by NaohisaSato** [comment]
10月27日　加工発注（図面　https://gwdoc.icrr.u-tokyo.ac.jp/cgi-bin/private/DocDB/ShowDocument）
11月19日納入期限

**Comment by MiyoKouseki** [comment]
納品されてインストールまち
